<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>

<!-- Meta Tags -->
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<meta name="description" content="StudyPress | Education & Courses HTML Template" />
<meta name="keywords" content="academy, course, education, education html theme, elearning, learning," />
<meta name="author" content="ThemeMascot" />

<!-- Page Title -->
<title>library</title>

<!-- Favicon and Touch Icons -->
<link href="images/title.png" rel="shortcut icon" type="image/png">
<link href="images/logo-wide.png" rel="apple-touch-icon">
<link href="images/logo-wide.png" rel="apple-touch-icon" sizes="72x72">
<link href="images/logo-wide.png" rel="apple-touch-icon" sizes="114x114">
<link href="images/logo-wide.png" rel="apple-touch-icon" sizes="144x144">
<link rel="icon" href="https://www.veritas.edu.ng/images/favicon.ico" type="image/x-icon" />
<!-- Stylesheet for form -->
<link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">
<!-- Main css register form-->
<!-- Stylesheet -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="css/jquery-ui.min.css" rel="stylesheet" type="text/css">
<link href="css/animate.css" rel="stylesheet" type="text/css">
<link href="css/css-plugin-collections.css" rel="stylesheet"/>
<!-- CSS | menuzord megamenu skins -->
<link id="menuzord-menu-skins" href="css/menuzord-skins/menuzord-rounded-boxed.css" rel="stylesheet"/>
<!-- CSS | Main style file -->
<link href="css/style-main.css" rel="stylesheet" type="text/css">
<link href="css/utility-classes.css" rel="stylesheet" type="text/css">

<!-- CSS | Preloader Styles -->
<link href="css/preloader.css" rel="stylesheet" type="text/css">
<!-- CSS | Custom Margin Padding Collection -->
<link href="css/custom-bootstrap-margin-padding.css" rel="stylesheet" type="text/css">
<!-- CSS | Responsive media queries -->
<link href="css/responsive.css" rel="stylesheet" type="text/css">
<!-- CSS | Style css. This is the file where you can place your own custom css code. Just uncomment it and use it. -->
<!-- <link href="css/style.css" rel="stylesheet" type="text/css"> -->
<script src="https://kit.fontawesome.com/13d098a0cf.js" crossorigin="anonymous"></script>
<!-- CSS | Theme Color -->
<link href="css/colors/theme-skin-color-set-1.css" rel="stylesheet" type="text/css">

<!-- external javascripts -->
<script src="js/jquery-2.2.4.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script src="js/bootstrap.min.js"></script>


<!-- JS | jquery plugin collection for this theme -->
<script src="js/jquery-plugin-collection.js"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<style>
    .card-horizontal {
    display: flex;
    flex: 1 1 auto;
}
</style>
</head>
<body class="bg-color-lightblue">
<div id="wrapper" class="clearfix">
 <!-- Header - Header -->
<?php include_once "includes/administration-navbar.php" ?>
  <!-- Start main-content -->
  <div class="main-content">
    <!-- Section: inner-header -->
    <?php include_once "includes/library-slider.php" ?>
          <!--------welcome section------------>
          <section class="mt-10">
            <div class="container bg-lightest">
              <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-9">
                    <div><h3 class="title text-navy text-bolder ml-10 text-uppercase">borrowing books from the library</h3></div>
                    <div></div>
                    <div id="accordion1" class="panel-group accordion pl-10">
                      <div class="panel cardi">
                        <div class="panel-title" > <a data-parent="#accordion1" data-toggle="collapse" href="#accordion11" class="" aria-expanded="true"> <span class="open-sub"></span> Who to meet for book Borrowing</a> </div>
                        <div id="accordion11" class="panel-collapse collapse" role="tablist" aria-expanded="true">
                          <div class="panel-content">
                            <h4 class="text-navy text-bolder">Confirmation of fees payment</h4>
                            <p class="text-black text-bold">Check online receipts generated by students with the bank payment schedules and or the fees payment portal (as the case may be); in order to confirm correctness and completeness of fees paid; then sign and stamp the receipts.</p>
                            <h4 class="text-navy text-bolder">Ledger Update</h4>
                            <p class="text-black text-bold">Each student’s ledger is updated automatically on-line after payment to reflect the current status, however, a back-up, manual ledger of every student is updated at the various School Accounts’ offices, with the online receipts and/or, follow-up print-out from the office of the Unit head.</p>
                           <h4 class="text-navy text-bolder">Opening Ledger for Fresh Students</h4>
                            <p class="text-black text-bold">Obtain the list of registered students from the admissions office/ Information Communication Technology Centre (ICTC).<br>Reconcile the list with the fees payment print-out of each Department/School to ensure full compliance.<br>Open ledger page each for a student serially in accordance with their Registration/Matriculation numbers.</p>
                          </div>
                        </div>
                      </div>
                      <div class="panel cardi">
                        <div class="panel-title"> <a class="collapsed" data-parent="#accordion1" data-toggle="collapse" href="#accordion12" aria-expanded="false"> <span class="open-sub"></span> What to Do</a> </div>
                        <div id="accordion12" class="panel-collapse collapse" role="tablist" aria-expanded="false" style="height: 0px;">
                          <div class="panel-content">
                            <h4 class="text-navy text-bolder">Confirmation of fees payment</h4>
                            <p class="text-black text-bold">Check online receipts generated by students with the bank payment schedules and or the fees payment portal (as the case may be); in order to confirm correctness and completeness of fees paid; then sign and stamp the receipts.</p>
                            <h4 class="text-navy text-bolder">Ledger Update</h4>
                            <p class="text-black text-bold">Each student’s ledger is updated automatically on-line after payment to reflect the current status, however, a back-up, manual ledger of every student is updated at the various School Accounts’ offices, with the online receipts and/or, follow-up print-out from the office of the Unit head.</p>
                           <h4 class="text-navy text-bolder">Opening Ledger for Fresh Students</h4>
                            <p class="text-black text-bold">Obtain the list of registered students from the admissions office/ Information Communication Technology Centre.<br>Reconcile the list with the fees payment print-out of each Department/School to ensure full compliance.<br>Open ledger page each for a student serially in accordance with their Registration/Matriculation numbers.</p>
                          </div>
                        </div>
                      </div>
                      <div class="panel cardi">
                        <div class="panel-title"> <a data-parent="#accordion1" data-toggle="collapse" href="#accordion13" class="collapsed" aria-expanded="false"> <span class="open-sub"></span>How to borrow a Book</a> </div>
                        <div id="accordion13" class="panel-collapse collapse" role="tablist" aria-expanded="false">
                          <div class="panel-content">
                            <p class="text-black text-bold">Payments are made to students in respect of Bursary awards, a refund of school fees due to wrong payment, overpayment or withdrawal from a programme, refund of hostel fees due to non-allocation of bed space, etc.</p>
                            <h4 class="text-navy text-bolder">Payment of Students Awards</h4>
                            <ul class="list">
                              <li class="text-black text-bold">Ascertain that there is due authority/approval for payment to be made</li>
                              <li class="text-black text-bold">Forward to Expenditure Control for commitment</li>
                              <li class="text-black text-bold">Raise payment voucher (PV)</li>
                              <li class="text-black text-bold">Forward voucher to Audit Unit for verification</li>
                              <li class="text-black text-bold">Forward audited PV to Cash Office for e-payment</li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="panel cardi">
                        <div class="panel-title"> <a data-parent="#accordion1" data-toggle="collapse" href="#accordion14" class="collapsed" aria-expanded="false"> <span class="open-sub"></span> criterial to borrow a book</a> </div>
                        <div id="accordion14" class="panel-collapse collapse" role="tablist" aria-expanded="false">
                          <div class="panel-content">
                            <p class="text-black text-bold">A letter of request by the student concerned is received with the appropriate approval for the refund or payment.</p>
                            <p class="text-black text-bold">The student’s teller is verified and a payment voucher is raised and signed by the Head of Unit before being sent to the Internal Audit Unit for pre-payment audit.</p>
                            <p class="text-black text-bold">The audited e-payment voucher is sent to the Cash Office for e-payment.</p>
                          </div>
                        </div>
                      </div>
                        <div><h3 class="title text-navy text-bolder ml-10 text-uppercase">Returning of borrowed books</h3></div>
                        <div></div>
                        <div class="panel cardi">
                            <div class="panel-title"> <a data-parent="#accordion1" data-toggle="collapse" href="#accordion16" class="collapsed" aria-expanded="false"> <span class="open-sub"></span> When to return a borrowed book</a> </div>
                            <div id="accordion16" class="panel-collapse collapse" role="tablist" aria-expanded="false">
                            <div class="panel-content">
                                <p class="text-black text-bold">Check the student ledgers to ensure full payment,</p>
                                <p class="text-black text-bold">Sign and stamp clearance form if not indebted to the University, otherwise, do not clear.</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel cardi">
                            <div class="panel-title"> <a data-parent="#accordion1" data-toggle="collapse" href="#accordion17" class="collapsed" aria-expanded="false"> <span class="open-sub"></span> book misplaced penalty</a> </div>
                            <div id="accordion17" class="panel-collapse collapse" role="tablist" aria-expanded="false">
                            <div class="panel-content">
                                <p class="text-black text-bold">Check the student ledgers to ensure full payment,</p>
                                <p class="text-black text-bold">Sign and stamp clearance form if not indebted to the University, otherwise, do not clear.</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel cardi">
                            <div class="panel-title"> <a data-parent="#accordion1" data-toggle="collapse" href="#accordion18" class="collapsed" aria-expanded="false"> <span class="open-sub"></span> Book retuning time </a> </div>
                            <div id="accordion18" class="panel-collapse collapse" role="tablist" aria-expanded="false">
                            <div class="panel-content">
                                <p class="text-black text-bold">Check the student ledgers to ensure full payment,</p>
                                <p class="text-black text-bold">Sign and stamp clearance form if not indebted to the University, otherwise, do not clear.</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel cardi">
                            <div class="panel-title"> <a data-parent="#accordion1" data-toggle="collapse" href="#accordion19" class="collapsed" aria-expanded="false"> <span class="open-sub"></span> Process of returnin a book</a> </div>
                            <div id="accordion19" class="panel-collapse collapse" role="tablist" aria-expanded="false">
                            <div class="panel-content">
                                <p class="text-black text-bold">Check the student ledgers to ensure full payment,</p>
                                <p class="text-black text-bold">Sign and stamp clearance form if not indebted to the University, otherwise, do not clear.</p>
                            </div>
                            </div>
                        </div>
                        </div>
                </div>
                <div class="col-md-3">
                  <table class="table table-bordered"> 
                    <tr>
                      <td class="text-center font-16 font-weight-600 bg-theme-colored text-white text-bolder" colspan="4">Feature Liniks</td>
                    </tr>
                    </table>
                  <div class="widget">
                  <?php include_once "includes/right-lib-link.php" ?>
              </div>
            </div>
            </div>
           </div>
        </section>
           <!-- Footer starts here -->
          <?php include_once "includes/footer.php" ?>
        <!-- Footer Scripts -->
<!-- JS | Custom script for all pages -->
<script src="js/custom.js"></script>
</body>
</html>
       
